# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 12:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(blank=True, default=b'', max_length=100)),
                ('lastname', models.CharField(blank=True, default=b'', max_length=100)),
                ('email', models.EmailField(default=b'', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message=b"Enter country code. Phone number must be entered in the format: '919999999'.", regex=b'^\\+?1?\\d{12}$')])),
                ('address_line_1', models.CharField(blank=True, default=b'', max_length=100)),
                ('address_line_2', models.CharField(blank=True, default=b'', max_length=100)),
                ('city', models.CharField(blank=True, default=b'', max_length=100)),
                ('pin_code', models.CharField(blank=True, default=b'', max_length=6, validators=[django.core.validators.RegexValidator(message=b'Enter pin code.', regex=b'^\\+?1?\\d{6}$')])),
                ('photo', models.TextField(blank=True, default=b'')),
                ('password', models.CharField(blank=True, default=b'', max_length=100)),
                ('access_token', models.CharField(blank=True, default=b'', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
