# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160123_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='fb_access_token',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='fb_token',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
