# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160123_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='fb_access_token',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='register',
            name='fb_id',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='register',
            name='google_access_token',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='register',
            name='google_id',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
