# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20160123_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='activation_key',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
