# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_register_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='activation_key_time',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
