# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_register_is_set_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='twitter_id',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='register',
            name='twitter_screen_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='register',
            name='twitter_token',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='register',
            name='twitter_token_secret',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
